definitions:
  models.Person:
    properties:
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: A RESTful API in Go to understand basics
  title: REST API Using Go
  version: "1.0"
paths:
  /persons:
    get:
      consumes:
      - application/json
      description: get all persons
      operationId: list-persons
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Person'
            type: array
      summary: List all persons
    post:
      consumes:
      - application/json
      description: Add a new person to the list
      operationId: create-person
      parameters:
      - description: Person object to be added
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/models.Person'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Person'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new person
  /persons/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a person by ID
      operationId: delete-person
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a person
    get:
      consumes:
      - application/json
      description: get person details by ID
      operationId: get-person-by-id
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Person'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get person details
    put:
      consumes:
      - application/json
      description: Update a person's details by ID
      operationId: update-person
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: string
      - description: Person object with updated details
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/models.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a person
swagger: "2.0"
